# Generated by Django 4.1.9 on 2023-05-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_secrets', '0006_alter_userkey_created_alter_userkey_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='_object_repr',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='secretrole',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
