# Generated by Django 5.0.6 on 2024-07-02 10:23

import taggit.managers
from django.db import migrations, models

import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0115_convert_dashboard_widgets'),
        ('netbox_secrets', '0007_secret__object_repr_secret_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AddField(
            model_name='userkey',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
