# Generated by Django 5.2.9 on 2026-01-13 13:16

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0134_owner'),
        ('netbox_secrets', '0008_userkey_custom_field_data_userkey_tags'),
        ('users', '0015_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='secretrole',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretrole',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretrole',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='secretrole',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='netbox_secrets.secretrole'),
        ),
        migrations.AddField(
            model_name='secretrole',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretrole',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secret',
            name='_object_repr',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secretrole',
            name='name',
            field=models.CharField(db_collation='natural_sort', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['assigned_object_type', 'assigned_object_id'], name='netbox_secr_assigne_2cc47e_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['role'], name='netbox_secr_role_id_258ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['_object_repr'], name='netbox_secr__object_2efed1_idx'),
        ),
        migrations.AddIndex(
            model_name='userkey',
            index=models.Index(fields=['user'], name='netbox_secr_user_id_2a9e10_idx'),
        ),
    ]
