# Generated by Django 5.1.6 on 2025-03-20 08:55

from django.db import migrations, models

def assign_userkey_is_active(apps, schema_editor):
    UserKey = apps.get_model('netbox_secrets', 'UserKey')
    for userkey in UserKey.objects.all():
        if userkey.master_key_cipher:
            userkey.is_active = True
            userkey.save()


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_secrets', '0008_userkey_custom_field_data_userkey_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='is_active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(assign_userkey_is_active)
    ]
