# Generated by Django 5.2.9 on 2026-01-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_secrets', '0009_secret_owner_secretrole_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
