# Generated by Django 5.2.10 on 2026-02-05 12:00

from django.db import migrations
import mptt
import mptt.managers

def rebuild_secretrole_tree(apps, schema_editor):
    manager = mptt.managers.TreeManager()
    SecretRole = apps.get_model("netbox_secrets", "SecretRole")
    manager.model = SecretRole
    mptt.register(SecretRole)
    manager.contribute_to_class(SecretRole, "objects")
    manager.rebuild()

class Migration(migrations.Migration):

    dependencies = [
        ('netbox_secrets', '0009_secret_owner_secretrole_level_secretrole_lft_and_more'),
    ]

    operations = [
        migrations.RunPython(code=rebuild_secretrole_tree, reverse_code=migrations.RunPython.noop),
    ]
