# Generated by Django 5.2.10 on 2026-05-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_secrets', '0010_secret_role_rebuild'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='secret',
            name='netbox_secr_role_id_258ca2_idx',
        ),
        migrations.RemoveIndex(
            model_name='secret',
            name='netbox_secr__object_2efed1_idx',
        ),
        migrations.RemoveIndex(
            model_name='userkey',
            name='netbox_secr_user_id_2a9e10_idx',
        ),
    ]
