# Generated by Django 5.2.9 on 2026-01-13 05:13

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_secrets', '0010_alter_userkey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretrole',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretrole',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretrole',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='netbox_secrets.secretrole'),
        ),
        migrations.AddField(
            model_name='secretrole',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretrole',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretrole',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='secretrole',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
