# Generated by Django 5.2.9 on 2026-01-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_secrets', '0011_secretrole_level_secretrole_lft_secretrole_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretrole',
            name='name',
            field=models.CharField(db_collation='natural_sort', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='secretrole',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
