# Generated by Django 6.1 on 2026-09-15 14:30

import django.db.models.deletion
import netbox.models.ltree
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_secrets', '0011_remove_redundant_indexes'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretrole',
            name='level',
        ),
        migrations.RemoveField(
            model_name='secretrole',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='secretrole',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='secretrole',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='secretrole',
            name='path',
            field=netbox.models.ltree.LtreeField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='secretrole',
            name='sort_path',
            field=models.TextField(blank=True, db_collation='natural_sort', default='', editable=False),
        ),
        migrations.AlterField(
            model_name='secret',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='secretrole',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='secretrole',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='netbox_secrets.secretrole'),
        ),
    ]
