# Generated by Django 6.1 on 2026-09-15 18:37

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0144_customfield_status'),
        ('netbox_secrets', '0012_remove_secretrole_level_remove_secretrole_lft_and_more'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretrole',
            options={'ordering': ['sort_path']},
        ),
        migrations.AddIndex(
            model_name='secretrole',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='secrets_secretrole_path_gist'),
        ),
        migrations.AddIndex(
            model_name='secretrole',
            index=models.Index(fields=['sort_path'], name='secrets_sr_sort_path_idx'),
        ),
    ]
