#!/bin/sh
# Create a link to this file at .git/hooks/pre-commit

exec 1>&2

EXIT=0
RED='\033[0;31m'
NOCOLOR='\033[0m'

echo "Running black..."
black .
if [ $? != 0 ]; then
	EXIT=1
fi

echo "Running isort..."
isort .
if [ $? != 0 ]; then
	EXIT=1
fi

echo "Running flake8..."
flake8 .
if [ $? != 0 ]; then
	EXIT=1
fi

if [ $EXIT != 0 ]; then
  printf "${RED}COMMIT FAILED${NOCOLOR}\n"
fi

exit $EXIT
