# Generated by Django 4.0.3 on 2022-04-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_secretstore', '0004_secretrole_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='secret',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secretrole',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='secretrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
