# Generated by Django 2.1.4 on 2019-02-20 06:56

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    replaces = [
        ('secrets', '0006_custom_tag_models')
    ]
    dependencies = [
        ('netbox_secretstore', '0005_change_logging'),
        ('extras', '0019_tag_taggeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
