# Generated by Django 3.2b1 on 2021-03-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_secretstore', '0013_standardize_models'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='secret',
            table=None,
        ),
        migrations.AlterModelTable(
            name='secretrole',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sessionkey',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userkey',
            table=None,
        ),
    ]
