name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    uses: Onemind-Services-LLC/actions/.github/workflows/python-publish.yml@7a5df58704eb175a5f377e0cb3d5172465977932
    with:
      runs-on: ubuntu-22.04-sh
      app-id: ${{ vars.APP_ID }}
    secrets:
      private-key: ${{ secrets.APP_PRIVATE_KEY }}
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}
