name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    uses: Onemind-Services-LLC/actions/.github/workflows/python-publish.yml@8ba8dea9401b08db920340ab52a47a0b3dd6e8d2
    with:
      runs-on: ubuntu-22.04-sh
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}
