name: Tests

permissions:
  contents: read

on:
  - push
  - pull_request

jobs:
  test:
    uses: Onemind-Services-LLC/actions/.github/workflows/netbox-plugin-tests.yml@master
    with:
      plugin_name: 'netbox_secrets'
      python_version: '3.12'
      netbox_version: 'v4.3.1'
    secrets:
      git_token: ${{ secrets.GIT_TOKEN }}
